// Here we implement our methods that are generated by tscodegen.
// Every function gets the JSI runtime. For most methods we do not
// need this.

#include "react-native-indy-vdr.h"
#include "../lib/cpp-generated/NativeModules.cpp"
#include "Logging.h"
#include "rust_header.h"

using namespace facebook;
using namespace react;

IndyVdr::IndyVdr(std::shared_ptr<CallInvoker> jsInvoker): IndyVdrCxxSpecJSI(jsInvoker) {};

double IndyVdr::set_config(jsi::Runtime &rt, const jsi::String &cfg) {
    ErrorCode error = indy_vdr_set_config(cfg.utf8(rt).c_str());
    return double(error);
}

jsi::String IndyVdr::version(jsi::Runtime &rt) {
    FfiStr indy_version = indy_vdr_version();
    jsi::String version = jsi::String::createFromAscii(rt, indy_version, strlen(indy_version));
    return version;
}

