/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>

namespace facebook {
namespace react {
class JSI_EXPORT IndyVdrCxxSpecJSI : public TurboModule {
public:
  IndyVdrCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);
  virtual jsi::String version(jsi::Runtime &rt) = 0;
  virtual void set_config(jsi::Runtime &rt, const jsi::Object &options) = 0;
  virtual void set_default_logger(jsi::Runtime &rt) = 0;
  virtual void set_protocol_version(jsi::Runtime &rt,
                                    const jsi::Object &options) = 0;
  virtual void set_socks_proxy(jsi::Runtime &rt,
                               const jsi::Object &options) = 0;
  virtual double
  build_acceptance_mechanisms_request(jsi::Runtime &rt,
                                      const jsi::Object &options) = 0;
  virtual double
  build_get_acceptance_mechanisms_request(jsi::Runtime &rt,
                                          const jsi::Object &options) = 0;
};

} // namespace react
} // namespace facebook
