/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>

namespace facebook {
namespace react {
class JSI_EXPORT IndyVdrCxxSpecJSI : public TurboModule {
public:
IndyVdrCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);
virtual jsi::String version(jsi::Runtime &rt) = 0;
virtual void set_config(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual void set_default_logger(jsi::Runtime &rt) = 0;
virtual void set_protocol_version(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual void set_socks_proxy(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_acceptance_mechanisms_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_acceptance_mechanisms_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_attrib_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_attrib_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_cred_def_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_cred_def_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_revoc_reg_def_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_revoc_reg_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_revoc_reg_delta_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_revoc_reg_def_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_custom_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_disable_all_txn_author_agreements_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_nym_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_schema_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_txn_author_agreement_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_txn_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_validator_info_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_nym_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_revoc_reg_entry_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_schema_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_txn_author_agreement_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_rich_schema_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_rich_schema_object_by_id_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double build_get_rich_schema_object_by_metadata_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double pool_create(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double pool_refresh(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double pool_get_status(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double pool_get_transactions(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double pool_get_verifiers(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double pool_submit_action(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double pool_submit_request(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double pool_close(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double prepare_txn_author_agreement_acceptance(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double request_free(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double request_get_body(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double request_get_signature_input(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double request_set_endorser(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double request_set_multi_signature(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double request_set_signature(jsi::Runtime &rt, const jsi::Object &options) = 0;
virtual double request_set_txn_author_agreement_acceptance(jsi::Runtime &rt, const jsi::Object &options) = 0;

};

} // namespace react
} // namespace facebook
