/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>

namespace facebook {
namespace react {
class JSI_EXPORT IndyVdrCxxSpecJSI : public TurboModule {
public:
IndyVdrCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);
virtual double set_config(jsi::Runtime &rt, const jsi::String &cfg) = 0;
virtual jsi::String version(jsi::Runtime &rt) = 0;

};

} // namespace react
} // namespace facebook
